EntityInstantiator
Timberborn-Modding-Central/TimberAPI pull request #7
Opened 2021-11-23 20:31 UTC by KYPremco

Changed name from Modifier to instantiator because it doesn't have to modify. And it hooks into the Instantiotor of Entity service hence EntityInstantiator.

Made the EntityInstantiator class internal to prevent confusion since it doesn't need to be used for the users.

2021-11-23 20:52 UTC, thundersen requested changes
Excellent stuff. Especially the examples are really great for understanding what this can do.
But I would suggest some naming changes.

2021-11-23 20:52 UTC, thundersen commented on TimberAPI/EntityInstantiator/EntityInstantiator.cs
> +    internal class EntityInstantiator
For me an `EntityInstantiator` would be a class that creates entity instances. But this class applies actions to `GameObject`s *when* they're instantiated.
How about `GameObjectActionApplier` for this class? Or something more catchy like `GameObjectTweaker`?
And consequently:
`TimberbornAPI.EntityInstantiatorSystem` -> `TimberbornAPI.GameObjectActions` or `TimberbornAPI.GameObjectTweaking`?
`IEntityInstantiator` -> `IGameObjectAction`?
`_gameObjectModifiers` -> `_instantiationActions`?
`visualElementInitializers` -> `instantiationActions`?

2021-11-23 20:52 UTC, thundersen commented on TimberAPIExample/Examples/GameObjectModifier/EntityInstantiatorConfigurator.cs
> +    public class EntityInstantiatorConfigurator : IInGameConfigurator
Don't forget to rename this as well, if we agree on something else than `EntityInstantiator`

2021-11-24 20:54 UTC, KYPremco commented
- Moved namspaces to folders
- Renamed the actions classes, interfaces
- Fixed creative construction example in update

2021-11-24 21:59 UTC, thundersen approved these changes

2021-11-24 22:03 UTC, merged